#pragma once
// Generated by native/tools/port_command_fields.rb; 32-bit cells in host byte order.
struct Command_00 {
    u32 value : 26;
    u32 code : 6;
};
struct Command_02 {
    u32 value : 26;
    u32 code : 6;
};
struct Command_03 {
    u32 value : 26;
    u32 code : 6;
};
struct Command_04 {
    u32 x;
};
struct Command_05 { u32 ptr; /* Serialized offset, resolved by archive owner. */ };
struct Command_07 { u32 ptr; /* Serialized offset, resolved by archive owner. */ };
struct Command_09 {
    u32 param_2 : 18;
    u32 param_1 : 8;
    u32 id : 6;
};
struct unk0 {
    u32 unk2 : 18;
    u32 unk1 : 8;
    u32 opcode : 6;
};
struct unk1 {
    u32 : 19;
    u32 unk2 : 1;
    u32 unk1 : 4;
    u32 unk0 : 2;
    u32 opcode : 6;
};
struct set_throw_flags {
    u32 hit_idx : 26;
    u32 opcode : 6;
};
struct unk3 {
    s32 unk1 : 25;
    s32 unk0 : 7;
};
struct unk4 {
    u32 : 18;
    u32 unk1 : 8;
    u32 opcode : 6;
};
struct unk5 {
    s32 unk1 : 18;
    s32 unk0 : 14;
};
struct unk6 {
    u32 : 25;
    u32 unk1 : 1;
    u32 opcode : 6;
};
struct set_airborne_state {
    u32 state : 26;
    u32 opcode : 6;
}; ///< #ftAction_80071998
struct unk8 {
    int unk0;
};
struct part_anim {
    u32 unk3 : 12;
    s32 unk2 : 7;
    s32 unk1 : 7;
    s32 opcode : 6;
};
struct unk9 {
    u32 unk2 : 13;
    u32 unk1 : 13;
    s32 unk0 : 6;
};
struct unk10 {
    u32 unk3 : 13;
    u32 unk2 : 12;
    u32 unk1 : 1;
    s32 unk0 : 6;
};
struct unk11 {
    u32 unk1 : 26;
    s32 unk0 : 6;
};
struct unk12 {
    u32 unk3 : 14;
    u32 unk2 : 10;
    u32 unk1 : 2;
    u32 unk0 : 6;
};
struct unk13 {
    u32 unk2 : 18;
    u32 unk1 : 8;
    u32 unk0 : 6;
};
struct unk14 {
    u32 : 18;
    u32 unk1 : 8;
    u32 unk0 : 6;
};
struct unk15 {
    u32 unk1 : 26;
    u32 unk0 : 6;
}; ///< #ftAction_80072B14
struct unk16 {
    s32 unk4 : 25;
    s32 unk3 : 1;
    u32 unk0 : 6;
}; ///< #ftAction_80072B3C
struct unk17 {
    s32 unk1 : 26;
    u32 unk0 : 6;
}; ///< #ftAction_80072B94
struct unk18 {
    s32 damage_amount : 26;
    u32 unk0 : 6;
}; ///< #ftAction_80072BF4
struct unk19 {
    u32 unk1 : 26;
    u32 unk0 : 6;
}; ///< #ftAction_80072C6C
struct unk20 {
    u32 unk1 : 26;
    u32 unk0 : 6;
}; ///< #ftAction_80072CB0
struct unk21 {
    u32 : 17;
    u32 unk2 : 8;
    u32 unk1 : 1;
    u32 unk0 : 6;
}; ///< #ftAction_800730B8
struct set_hitbox_damage {
    u32 value : 23;
    u32 idx : 3;
    u32 opcdoe : 6;
}; ///< #ftAction_8007162C
struct set_hitbox_scale {
    u32 value : 23;
    u32 idx : 3;
    u32 opcode : 6;
}; ///< #ftAction_8007169C
struct set_hitbox_x42_b57 {
    u32 value : 1;
    u32 type : 1;
    u32 idx : 24;
    u32 opcode : 6;
}; ///< #ftAction_80071708
struct set_cmd_var {
    u32 value : 24;
    u32 idx : 2;
    u32 opcode : 6;
}; ///< #ftAction_80071708
struct set_hurt_state {
    u32 state : 18;
    u32 bone_idx : 8;
    u32 opcode : 6;
}; ///< #ftAction_80071A9C
struct set_jab_combo {
    u32 disabled : 26;
    u32 opcode : 6;
}; ///< #ftAction_80071AE8
struct set_jab_rapid {
    u32 state : 26;
    u32 opcode : 6;
}; ///< #ftAction_80071B28
struct set_dobj_flags {
    s32 value : 19;
    s32 idx : 7;
    u32 opcode : 6;
}; ///< #ftAction_80071D40
struct set_throw_hitbox_0 {
    u32 damage : 23;
    u32 idx : 3;
    u32 opcode : 6;
}; ///< #ftAction_80071E04
struct set_throw_hitbox_1 {
    u32 : 5;
    u32 hit_x28 : 9;
    u32 hit_x24 : 9;
    u32 unk0 : 9;
}; ///< #ftAction_80071E04
struct set_throw_hitbox_2 {
    u32 : 12;
    u32 sfx_kind : 4;
    u32 sfx_severity : 3;
    u32 element : 4;
    u32 hit_x2C : 9;
}; ///< #ftAction_80071E04
struct unk27 {
    u32 value : 26;
    u32 opcode : 6;
}; ///< #ftAction_80071F34
struct set_article_vis {
    u32 value : 26;
    u32 opcode : 6;
}; ///< #ftAction_80071F78
struct set_fighter_vis {
    u32 value : 26;
    u32 opcode : 6;
}; ///< #ftAction_80071FA0
struct set_tex_anim {
    s32 frame : 11;
    s32 idx2 : 7;
    s32 idx : 7;
    u32 b : 1;
    u32 opcode : 6;
}; ///< #ftAction_800726F4
struct unk31 {
    u32 unk1 : 16;
    u32 unk0 : 10;
    u32 opcode : 6;
}; ///< #ftAction_80073008
struct unk32 {
    u32 unk1 : 13;
    u32 unk0 : 13;
    u32 opcode : 6;
}; ///< #ftAction_80073008
struct unk33 {
    u32 unk1 : 13;
    u32 unk0 : 13;
    u32 opcode : 6;
}; ///< #it_8027990C
struct spawn_gfx_0 {
    u32 unk1 : 15;
    u32 useUnkBone : 1;
    u32 destroyOnStateChange : 1;
    u32 useCommonBoneIDs : 1;
    u32 boneId : 8;
    u32 opcode : 6;
};
struct spawn_gfx_1 {
    u32 unkFloat : 16;
    u32 gfxID : 16;
};
struct spawn_gfx_2 {
    s32 offsetY : 16;
    s32 offsetZ : 16;
};
struct spawn_gfx_3 {
    u32 rangeZ : 16;
    s32 offsetX : 16;
};
struct spawn_gfx_4 {
    u32 rangeX : 16;
    u32 rangeY : 16;
};
struct spawn_hitbox_0 {
    u32 damage : 10;
    u32 use_common_bone_ids : 1;
    u32 bone : 8;
    u32 only_hit_grabbed : 1;
    u32 hit_group : 3;
    u32 id : 3;
    u32 opcode : 6;
};
struct spawn_hitbox_1 {
    s32 z_offset : 16;
    u32 size : 16;
};
struct spawn_hitbox_2 {
    s32 x_offset : 16;
    s32 y_offset : 16;
};
struct spawn_hitbox_3 {
    u32 rebound : 1;
    u32 clank : 1;
    u32 ignore_fighter_scale : 1;
    u32 ignore_thrown_fighters : 1;
    u32 item_hit_interaction : 1;
    u32 weight_set_knockback : 9;
    u32 knockback_growth : 9;
    u32 angle : 9;
};
struct spawn_hitbox_4 {
    u32 hit_aerial : 1;
    u32 hit_grounded : 1;
    u32 hit_sfx_kind : 5;
    u32 hit_sfx_severity : 3;
    s32 shield_damage : 8;
    u32 element : 5;
    u32 base_knockback : 9;
};
struct spawn_hitbox_5 {
    u32 : 16;
    u32 x1_b7 : 1;
    u32 x1_b6 : 1;
    u32 x1_b5 : 1;
    u32 x1_b4 : 1;
    u32 x1_b3 : 1;
    u32 x1_b2 : 1;
    u32 x1_b1 : 1;
    u32 x1_b0 : 1;
    u32 x0 : 8;
};
struct it_create_hitbox_0 {
    u32 damage : 13;
    u32 bone : 7;
    u32 hit_group : 3;
    u32 id : 3;
    u32 opcode : 6;
};
struct it_create_hitbox_4 {
    u32 x40_b2 : 1;
    u32 x40_b3 : 1;
    u32 sfx_kind : 4;
    u32 sfx_severity : 3;
    s32 shield_damage : 8;
    u32 x40_b0 : 1;
    u32 element : 5;
    u32 base_knockback : 9;
};
struct spawn_hitbox_skip {
    u32 words[3];
    u32 : 3;
    u32 xF_b4 : 1;
    u32 xF_b3 : 1;
    u32 xF_b2 : 1;
    u32 xF_b1 : 1;
    u32 xF_b0 : 1;
    u32 : 24;
};
struct sound_effect_0 {
    u32 unknown : 18;
    u32 behavior : 8;
    u32 opcode : 6;
};
struct sound_effect_1 {
    u32 sfx_id;
};
struct sound_effect_2 {
    u32 panning : 8;
    u32 volume : 8;
    u32 padding : 16;
};
struct pseudo_random_sfx_0 {
    u32 random_range : 6;
    u32 behavior : 4;
    u32 panning : 8;
    u32 volume : 8;
    u32 opcode : 6;
};
struct pseudo_random_sfx_1 {
    u32 sfx_id;
};
struct stage_sfx_0 {
    u32 pitch_select : 8;
    u32 x2_b0_7 : 8;
    u32 sfx_base : 10;
    u32 opcode : 6;
};
struct stage_sfx_1 {
    u32 sfx_id;
};
struct stage_sfx_2 {
    u32 x2_b0_15 : 16;
    u32 x0_b0_15 : 16;
};
struct stage_sfx_3 {
    u32 x3_b0_7 : 8;
    u32 x2_b0_7 : 8;
    u32 x0_b0_15 : 16;
};
struct footstep_fx_0 {
    u32 x3_b0_7 : 8;
    u32 x2_b0_7 : 8;
    u32 x1_b7 : 1;
    u32 use_alt_bone : 1;
    u32 boneId : 8;
    u32 opcode : 6;
};
struct unk_fx_0 {
    u32 x3_b0_7 : 8;
    u32 x2_b0_7 : 8;
    u32 x1_b0_7 : 8;
    u32 x0_b6_7 : 2;
    u32 opcode : 6;
};
struct smash_charge_0 {
    u32 charge_rate : 16;
    u32 charge_frames : 10;
    u32 opcode : 6;
};
struct smash_charge_1 {
    u32 x1_b0_23 : 24;
    u32 color_anim : 8;
};
struct wind_fx_0 {
    u32 bone : 8;
    u32 x0_b6_17 : 18;
    u32 opcode : 6;
};
struct wind_fx_1 {
    s32 x : 16;
    s32 timer : 16;
};
struct wind_fx_2 {
    s32 mag : 16;
    s32 y : 16;
};
struct wind_fx_3 {
    s32 decay : 16;
    s32 angle : 16;
};
