# Generate little-endian views of the game's serialized 32-bit command cells.
# Original declarations remain in lb/types.h for the matching PowerPC build.
path = File.expand_path('../../src/melee/lb/types.h', __dir__)
source = File.read(path)
section = source[source.index('struct Command_00 {')...source.index('struct CommandInfo {')]
raise 'Command section missing' unless section
section = section.sub(/\n#endif\s*\z/, "\n")
count = 0
result = section.gsub(/struct (\w+) \{(.*?)\n\};/m) do |block|
  name, body = $1, $2
  fields = body.lines.reject { |line| line.strip.empty? }
  parsed = fields.map { |line| line.match(/^\s*([us])(?:8|16|32)\s+(\w+)\s*:\s*(\d+);/) }
  if parsed.all?
    width = parsed.sum { |field| field[3].to_i }
    raise "Oversized command #{name}" if width > 32
    count += 1
    bits = width < 32 ? ["    u32 : #{32-width};"] : []
    bits += parsed.reverse.map { |field| "    #{field[1]}32 #{field[2]} : #{field[3]};" }
    "struct #{name} {\n#{bits.join("\n")}\n};"
  elsif ['Command_05', 'Command_07'].include?(name)
    "struct #{name} { u32 ptr; /* Serialized offset, resolved by archive owner. */ };"
  elsif name == 'spawn_hitbox_skip'
    "struct spawn_hitbox_skip {\n    u32 words[3];\n    u32 : 3;\n    u32 xF_b4 : 1;\n    u32 xF_b3 : 1;\n    u32 xF_b2 : 1;\n    u32 xF_b1 : 1;\n    u32 xF_b0 : 1;\n    u32 : 24;\n};"
  else
    raise "Unhandled command layout #{name}" if body.include?(':')
    block
  end
end
File.write(File.expand_path('../include/native_command_fields.h', __dir__), "#pragma once\n// Generated by native/tools/port_command_fields.rb; 32-bit cells in host byte order.\n" + result)
puts "Generated #{count} command bitfield views"
