#pragma once
#include <stddef.h>
#ifdef __cplusplus
extern "C" {
#endif
enum MeleeAssetType {
    AT_NONE, AT_STRING, AT_RAW, AT_WORDS, AT_VEC3, AT_MTX,
    AT_SCENE, AT_MODELS, AT_MODEL, AT_CAMERAS, AT_CAMERA,
    AT_LIGHT_LISTS, AT_LIGHT_LIST, AT_LIGHT, AT_WOBJ,
    AT_JOINT, AT_DOBJ, AT_MOBJ, AT_MATERIAL, AT_PE, AT_TOBJ,
    AT_IMAGE, AT_TLUT, AT_LOD, AT_TEV, AT_POBJ, AT_VERTICES,
    AT_ENVELOPES, AT_ENVELOPE, AT_ANIMS, AT_ANIM, AT_AOBJ, AT_FOBJ,
    AT_MATANIMS, AT_MATANIMJOINT, AT_MATANIM, AT_TEXANIM,
    AT_CAMERA_ANIMS, AT_CAMERA_ANIM, AT_WOBJ_ANIM, AT_LIGHT_ANIMS, AT_LIGHT_ANIM,
    AT_IMAGES, AT_TLUTS, AT_HALVES, AT_TROPHIES, AT_TROPHY_DISPLAY, AT_SHAPEJOINT, AT_SHAPEDOBJ, AT_SHAPEANIM, AT_FOG, AT_FOGADJ, AT_SOBJ, AT_REFRACT, AT_EVENTS, AT_EVENT, AT_EVENT_INIT, AT_EVENT_BONUS, AT_EVENT_STAGE, AT_EVENT_PLAYER, AT_EVENT_EXTRA, AT_EVENT_TIMING, AT_WORD_TABLE, AT_SHAPESET, AT_RAW_TABLE, AT_CPU_VERTICES, AT_EFFECTDESC, AT_SPLINE, AT_PTCL_LIST, AT_PLAYER_COMMON, AT_FT_COMMON, AT_FT_PARTS, AT_FT_PARTS_TABLE, AT_BYTEPAIR, AT_BYTEPAIR_TABLE, AT_SHAKE, AT_COLOR_DESC, AT_CPU_CONFIG, AT_JOINT_ANIM_PAIR, AT_SCRIPT, AT_MAP_HEAD, AT_MAP_MODEL, AT_MAP_JOINT_PAIRS, AT_SPLINE_TABLE, AT_JOINT_TABLE, AT_LIGHT_OVERRIDE, AT_SHADOW_ENTRY, AT_COLL_MAP, AT_MAP_JOINT, AT_GROUND_PARAM, AT_STAGE_PARAM, AT_SHAPEANIMS, AT_MOBJ_TABLE, AT_SCRIPT_TABLE, AT_ITEM_PUBLIC, AT_ARTICLES, AT_ARTICLE, AT_ITEM_COMMON, AT_ITEM_ATTR, AT_ITEM_HURT, AT_ITEM_STATES, AT_ITEM_MODEL, AT_ITEM_DYNAMICS, AT_BONE_DYNAMICS, AT_ITEM_NUMBERS, AT_ITEM_FOODS, AT_ITEM_KINOKO, AT_ITEM_WSTAR, AT_ITEM_LEADEAD, AT_ITEM_OCTA, AT_ITEM_OTTO, AT_ITEM_KURI, AT_ITEM_TIERS, AT_ITEM_UNKNOWN, AT_ROBJ_ANIM, AT_ROBJ, AT_RVALUES, AT_EXPRESSION, AT_BYTE_EXPRESSION, AT_FIGHTER, AT_FIGHTER_ATTR, AT_FIGHTER_PARTS, AT_FIGHTER_VIS_TABLE, AT_FIGHTER_VIS, AT_PART_VIS, AT_HALF_TABLE, AT_FIGHTER_ANIMS, AT_FIGHTER_PART_ANIM_TABLE, AT_FIGHTER_PART_ANIM, AT_FIGHTER_GUARD, AT_FIGHTER_DYNAMICS, AT_FIGHTER_HURT, AT_FIGHTER_LEDGE, AT_FIGHTER_SFX, AT_SFX_ARRAY, AT_FIGHTER_IK, AT_FIGHTER_ITEMS, AT_FIGATREE, AT_FIGATRACKS, AT_FIGATREES, AT_FIGATREE_TABLES, AT_SCENE_FOG, AT_ITEM_CLIMBER_STRING, AT_ITEM_BOOMERANG, AT_ITEM_HOOKSHOT, AT_ITEM_ARROW, AT_ITEM_GRAPPLE, AT_ITEM_CHAIN, AT_ITEM_YOYO, AT_ITEM_GW, AT_ITEM_CHEF, AT_SAMUS_BEAM, AT_PURIN_PARTS, AT_KIRBY_COPY_FOX, AT_GAMEWATCH_ATTR, AT_GROUND_ITEMS, AT_GROUND_ITEM, AT_ITEM_POINTER_WORDS, AT_ITEM_WHITEBEA, AT_ITEM_TINCLE, AT_ITEM_APPLE, AT_STAGE_ICE, AT_DYNAMICS_DESC, AT_ITEM_DRAW_PARTS, AT_ITEM_SWORD, AT_KIRBY_COPY_YOSHI, AT_COUNT
};
enum MeleeAssetFieldKind { AF_BYTE=1, AF_HALF=2, AF_WORD=4, AF_POINTER=8 };
typedef struct MeleeAssetField { unsigned file_offset; size_t host_offset; unsigned kind, count, target; } MeleeAssetField;
typedef struct MeleeAssetSchema { unsigned file_size; size_t host_size; const MeleeAssetField* fields; unsigned field_count; } MeleeAssetSchema;
const MeleeAssetSchema* MeleeNativeAssetSchema(unsigned type);
unsigned MeleeNativeItemSpecialType(unsigned kind);
void MeleeNativeItemFlags(void* data, unsigned first, unsigned second);
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
void MeleeNativeEventFlags(void* data, unsigned flags, unsigned hi, unsigned lo);
#ifdef __cplusplus
}
#endif
